apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: configmap-policy-git
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: null
    policy.open-cluster-management.io/categories: null
    policy.open-cluster-management.io/controls: null
spec:
  remediationAction: inform
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: configmap-policy-git-prod-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
              - openshift-*
            include:
              - '*'
          object-templates:
            - complianceType: mustnothave
              objectDefinition:
                apiVersion: v1
                data:
                  key1: value1
                  key2: value2
                kind: ConfigMap
                metadata:
                  name: my-gitops-config
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-configmap-policy-git
  namespace: policies
placementRef:
  name: placement-configmap-policy-git
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: configmap-policy-git
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-configmap-policy-git
  namespace: policies
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: class
        operator: In
        values:
          - learning
