apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: gatekeeper-labeling-policy
policyDefaults:
  namespace: policies
  placement:
    placementRulePath: input/placementrule.yaml
  remediationAction: inform
  severity: medium
policies:
  - name: gatekeeper-require-ns-labels
    disabled: false
    manifests:
      - path: input/gatekeeper.yaml
    namespaceSelector:
      exclude:
        - kube-*
        - openshift-*
      include:
        - "*"
